apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jupyter
  name: jupyter-notebook-volume-claim
  labels:
    app: jupyter-notebook
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
