apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    app: jupyter-notebook
  namespace: jupyter
  name: jupyter-notebook
spec:
  type: NodePort
  ports:
    - name: http
      port: 8090
      targetPort: 8090
      nodePort: 30090
  selector:
    app: jupyter-notebook
