name: iceberg-mgc

services:
  broker:
    image: apache/kafka:latest
    container_name: kafka
    healthcheck:
      test: /opt/kafka/bin/kafka-cluster.sh cluster-id --bootstrap-server broker:9092 || exit 1
      interval: 1s
      timeout: 20s
      retries: 60
    ports:
      - "9092:9092"
    volumes:
      - ./data:/var/lib/kafka/data

  postgresql:
    hostname: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: iceberg-postgres
    ports:
      - 5432:5432

#  producer-service:
#    command: uv run /app/iceberg_services/kafka_producer.py
#    restart: always
#    build:
#      context: .
#      dockerfile: iceberg_services/Dockerfile
#    depends_on:
#      broker:
#        condition: service_healthy
#    environment:
#      KAFKA_BROKER: broker:9092
#
#  consumer-service:
#    command: uv run /app/iceberg_services/kafka_consumer.py
#    restart: always
#    build:
#      context: .
#      dockerfile: iceberg_services/Dockerfile
#    depends_on:
#      broker:
#        condition: service_healthy
#      postgresql:
#        condition: service_started
#    environment:
#      KAFKA_BROKER: broker:9092
#      POSTGRES_SERVER: postgresql:5432
#      PYICEBERG_HOME: /app
