apiVersion: v1
kind: Service
metadata:
  namespace: kafka
  name: kafka-service
  labels:
    app: kafka
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
    - name: kafka
      protocol: TCP
      port: 9092
      targetPort: 9092
